# This is the main configuration file for your Jekyll site.
# - If you find yourself editing this file very often, consider using Jekyll's data files feature
#   for the data you need to update frequently.
# - If updated, restart webserver.

# SETTINGS
# - Variables in this file are accessed via {{ site.title }}, {{ site.email }}, and so on.
# - You can create any custom variable you would like, such as {{ site.myvariable }}.
title: DAFx25 - Antiderivative Antialiasing for Recurrent Neural Networks
email: otto@soundtoys.com
description: >- # this means to ignore newlines until "baseurl:"
  Accompanying webpage for article "Antiderivative Antialiasing for Recurrent Neural Networks" in Proc. DAFx25.
baseurl: "/dafx25-adaa-for-rnns" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username: jekyll
header_pages:
  # - about.markdown
  - index.markdown
  - additional_results.markdown
  - additional_models.markdown

# BUILD
theme: minima # others: minimal-mistakes-jekyll, jekyll-theme-minimal
# remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
#
# EXCLUDES
# - The following items will not be processed, by default.
# - Any item listed under the `exclude:` key here will be automatically added to the internal
#   "default list".
# - Excluded items can be processed by explicitly listing the directories or their entries' file
#   path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
